name: Beta Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.3'
      - name: Install dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm i

      - name: Build
        run: npm run build
      
      - name: remove vendor and node_modules
        run: |
          rm -rf vendor
          rm -rf node_modules

      - name: Create release branch and bump version
        run: sed -i "s/    'version' => 'development',/    'version' => 'beta',/" config/app.php

      - name: Add commit sha to app.php
        run: sed -i "s/    'commit' => '',/    'commit' => '${{ github.sha }}',/" config/app.php

      - name: Create beta archive
        run: |
          rm -rf node_modules tests CODE_OF_CONDUCT.md CONTRIBUTING.md flake.lock flake.nix phpstan.neon phpunit.xml shell.nix
          tar -czf paymenter.tar.gz * .env.example .gitignore

      - name: Create checksum and add to changelog
        run: |
          SUM=`sha256sum paymenter.tar.gz`
          echo $SUM > checksum.txt
          
      # Add to action file
      - uses: actions/upload-artifact@v4
        with:
            name: paymenter
            path: paymenter.tar.gz