name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pint:
    if: github.event_name == 'push' && contains(github.ref, 'refs/heads/master')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: bcmath, curl, gd, mbstring, mysql, openssl, pdo, tokenizer, xml, zip
          tools: composer:v2
          coverage: none

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Pint
        run: vendor/bin/pint

      - name: Commit Pint Fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: linted files with pint"
          branch: master
          file_pattern: "*.php"

  #phpstan:
    #runs-on: ubuntu-latest

    #steps:
      #- name: Checkout code
        #uses: actions/checkout@v4

      #- name: Setup PHP
        #uses: shivammathur/setup-php@v2
        #with:
          #php-version: '8.3'
          #extensions: bcmath, curl, gd, mbstring, mysql, openssl, pdo, tokenizer, xml, zip
          #tools: composer:v2
          #coverage: none

      #- name: Cache Composer Dependencies
        #uses: actions/cache@v3
        #with:
          #path: ~/.composer/cache
          #key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          #restore-keys: ${{ runner.os }}-composer-

      #- name: Install Dependencies
        #run: composer install --no-interaction --no-progress --prefer-dist 

      #- name: Run PHPStan
        #run: vendor/bin/phpstan analyse
